### ISSUE TITLE
defaultValue doesn't update

### ISSUE THREAD

**Issue by sobernaut** [sharingapples/widgets#45]
Form's defaultValue does not update when new defaultValue is provided.

**Comment by syaau** [comment]
The `defaultValue` is not supposed to changed over the lifetime of the form. This would create unintended effects. Rather use something like a `HiddenInput` if you are looking for changing intrinsic values.

```javascript
function HiddenInput({ name, value }) {
  const [, onChange] = useFormInput(name, value);
  onChange(value);
}
```
